### ISSUE TITLE
怎么关掉双击关闭标签页

### ISSUE THREAD

**Issue by Sokoula** [shuax/chrome_plus#12]
我是手动点x，点的过快就会一连关掉好几个标签页，很影响使用，有配置页面或者配置文件可以改吗

**Comment by shuaiyewl** [comment]
用 Chrome++1.4.2版就行了，1.4.2版在Chrome100下正好是双击功能失效的。

**Comment by Sokoula** [comment]
> 用 Chrome++1.4.2版就行了，1.4.2版在Chrome100下正好是双击功能失效的。

可以了感谢
