### ISSUE TITLE
大佬，Chrome++ v1.5.2在最新版失效。

### ISSUE THREAD

**Issue by cc19264997** [shuax/chrome_plus#17]
无法实现滚轮切换标签页。我用的Google Chrome v101.0.4951.64

**Comment by shuax** [comment]
![image](https://user-images.githubusercontent.com/6940583/167996883-bf2aadd9-6c63-44f0-9acd-8583ba05dfd0.png)
测试没问题啊

**Comment by WeaponJang** [comment]
101.0.4951.64（64位），Chrome++ 1.5.2，Windows 10 x64，完美可用

**Comment by cc19264997** [comment]
找到了原因   开启MouseInc的鼠标穿透 会导致chrome++滚轮切换标签页失效。！希望修复
@shuax

**Comment by cc19264997** [comment]
> ![image](https://user-images.githubusercontent.com/6940583/167996883-bf2aadd9-6c63-44f0-9acd-8583ba05dfd0.png) 测试没问题啊

找到了原因 开启MouseInc的鼠标穿透 会导致chrome++滚轮切换标签页失效。！希望修复

**Comment by alnhny** [comment]
你用的win10以下的系统么，win10及以上的直接支持“滚轮穿透”。

**Comment by cc19264997** [comment]
> 你用的win10以下的系统么，win10及以上的直接支持“滚轮穿透”。

用的win10-21H2。哈哈，已经取消勾选，现在正常了。
