### ISSUE TITLE
能否恢复 chrome 离线包 API 

### ISSUE THREAD

**Issue by sino1641** [shuax/chrome_plus#18]
之前 shuax 网站有搭配离线包下载的 API ，后来随 chrome++ 关闭而关闭了。
请问作者是否还有留存该 api 的源码，能否将其恢复或公开供用户自行部署？
十分感谢！

**Comment by shuax** [comment]
网上很多其他人的，随便找个用就是了

**Comment by Ryanjiena** [comment]
https://raw.iqiq.io/Ryanjiena/MetaVersion/main/chrome.json

**Comment by shuax** [comment]
https://github.com/shuax/chrome_installer

用GitHub actions做了个每天自动抓，不知道能用不
