### ISSUE TITLE
希望增加在新窗口打开书签的功能

### ISSUE THREAD

**Issue by jarod360** [shuax/chrome_plus#19]
大佬：希望增加在新窗口打开书签的功能，如有打扰请忽略。

**Comment by 9dark9** [comment]
https://greasyfork.org/zh-CN/scripts/429714-新标签页打开链接

用这个就可以了

**Comment by jarod360** [comment]
书签不起作用呀。还是当前窗口打开呀

**Comment by 9dark9** [comment]
看错了，鼠标中键点击书签
