### ISSUE TITLE
请问如何让chrome的图标在任务栏不叠加在一起？

### ISSUE THREAD

**Issue by klgd** [shuax/chrome_plus#25]
原版chrome 似乎通过命令行参数不同 打开的chrome就不会在任务栏叠加在一起
用了`version.dll`后是全都叠加到一起了，请问该如何像原版那样分开来呢

**Comment by yijiangchengming** [comment]
windows设置-个性化-任务栏-合并任务栏-从不

**Comment by klgd** [comment]
> windows设置-个性化-任务栏-合并任务栏-从不

这样的话 所以的软件都会平铺开的   
不是我想要的
