### ISSUE TITLE
用v88版本的chrome，怎么关闭无法更新chrome的弹窗提示？

### ISSUE THREAD

**Issue by iwsbiwy** [shuax/chrome_plus#27]
每次打开都弹出这个，怎么让它不弹出？
[![jBKTld.png](https://s1.ax1x.com/2022/07/08/jBKTld.png)](https://imgtu.com/i/jBKTld)

**Comment by Bush2021** [comment]
老时间炸弹了
调整电脑时间 or 更新版本

**Comment by iwsbiwy** [comment]
> 老时间炸弹了 调整电脑时间 or 更新版本

这两个都不好弄啊，调电脑时间不方便，新版本，有些网页兼容性有问题。

**Comment by zichenw** [comment]
添加到Chrome的快捷方式路径后面 --simulate-outdated-no-au='Tue, 31 Dec 2099 23:59:59 GMT'

**Comment by iwsbiwy** [comment]
> 添加到Chrome的快捷方式路径后面 --simulate-outdated-no-au='Tue, 31 Dec 2099 23:59:59 GMT'

你好，请问是按▼【下图】设置吗？
![](https://s3.bmp.ovh/imgs/2022/07/31/95f0557fc8c4fa8e.png)
设置后发现两个问题
![](https://s3.bmp.ovh/imgs/2022/07/31/f281d1179a86b9c2.png)
chrome版本是v88

**Comment by zichenw** [comment]
> > 添加到Chrome的快捷方式路径后面 --simulate-outdated-no-au='Tue, 31 Dec 2099 23:59:59 GMT'
> 
> 你好，请问是按▼【下图】设置吗？ ![](https://camo.githubusercontent.com/6a052722aad245ece9e4174436b6d9bf463cf29aeb1088cc22feeee6d5c2cc9c/68747470733a2f2f73332e626d702e6f76682f696d67732f323032322f30372f33312f393566303535376663386334666138652e706e67) 设置后发现两个问题 ![](https://camo.githubusercontent.com/b3ca4761826cfb94f68dffa2c2ea1d2d3225239fa13eaee6f2326e85ea6b97f3/68747470733a2f2f73332e626d702e6f76682f696d67732f323032322f30372f33312f663238316431313739613836623963322e706e67) chrome版本是v88

把单引号改成双引号就可以，这个只是没有弹窗，但右上角的更新字样还是存在。
最彻底的方法是加`--disable-background-networking` 禁用chrome的网络进程，再也不会收到更新弹窗，但自带的翻译和扩展的更新会连不上
没有完美的解决办法，更新弹窗是内置在浏览器里的除非去编译源码，反正就开浏览器时弹一次，开着不要关就好

**Comment by iwsbiwy** [comment]
> --simulate-outdated-no-au='Tue, 31 Dec 2099 23:59:59 GMT'

好的，谢谢你了，我还是用edge吧，chrome作大死啊。
