### ISSUE TITLE
新版version.dll对于全新chrome不能同步扩展

### ISSUE THREAD

**Issue by pirately** [shuax/chrome_plus#3]
大大，新版version.dll插件，对于全新的chrome，貌似不能同步chrome的扩展，用老版配100版的chrome倒是可以同步，但是不能双击。

**Comment by Itzamana** [comment]
在论坛帖子里看到，1.5.0是有个基本不影响使用的小bug…
https://bbs.kafan.cn/forum.php?mod=redirect&goto=findpost&ptid=1419691&pid=50733212&fromuid=1048888

**Comment by shuax** [comment]
https://github.com/shuax/chrome_plus/blob/main/src/portable.h#L111

应该是这一行吧，你可以fork以后，自己改一下试试

**Comment by pirately** [comment]
> https://github.com/shuax/chrome_plus/blob/main/src/portable.h#L111
> 
> 应该是这一行吧，你可以fork以后，自己改一下试试

多谢。在 *111* 行前加 `//` 试了一下，应该可以了。
