### ISSUE TITLE
打开两个标签页的时候其中一个标签页在播放视频，关闭另外一个标签页会自动再生成一个新的标签页

### ISSUE THREAD

**Issue by conan4803** [shuax/chrome_plus#4]
麻烦shuax看看kfan这个帖子，谢谢。
https://bbs.kafan.cn/forum.php?mod=redirect&goto=findpost&ptid=1419691&pid=50742861&fromuid=628471

**Comment by shuax** [comment]
应该是带有音量的标签页识别错了。

**Comment by shuax** [comment]
1.5.1 应该已经修复

**Comment by conan4803** [comment]
> 1.5.1 应该已经修复

已更新，实测已修复，感谢shuax大大。
