### ISSUE TITLE
请问能修改Cache缓存文件的位置么?

### ISSUE THREAD

**Issue by star2k** [shuax/chrome_plus#6]
如题，默认在浏览器目录，我想修改到内存缓存盘

**Comment by shuax** [comment]
https://github.com/shuax/chrome_plus/blob/c00266a0577015be4af1e6d01590d0693a90530b/src/portable.h#L58

你fork了自己改一下

**Comment by star2k** [comment]
![Snipaste_2022-04-09_08-48-18](https://user-images.githubusercontent.com/9582078/162549969-90dd9878-5ba1-4012-86c7-2a088ab1bc5c.png)
直接这样插入盘符么？

**Comment by shuax** [comment]
不是……你用mklink创建软连接吧

**Comment by star2k** [comment]
好的，新手见笑了。

**Comment by zhifeiyue** [comment]
chrome本身有一个命令行开关可以指定cache的位置：--disk-cache-dir，比如 --disk-cache-dir=R:\Chrome_tmp

**Comment by star2k** [comment]
> chrome本身有一个命令行开关可以指定cache的位置：--disk-cache-dir，比如 --disk-cache-dir=R:\Chrome_tmp

建立桌面快捷方式时候加入是吧，我试试
