### ISSUE TITLE
1.5.1 使用过程中会出现保存网页图片时，浏览器界面自动跳到其他打开的应用后面（变为非当前界面）

### ISSUE THREAD

**Issue by Soizzer** [shuax/chrome_plus#8]
1.5.1 使用过程中会出现：当保存网页图片时，浏览器界面自动跳到其他打开的应用后面（变为非当前界面）
1.5 则没有遇到该问题。

浏览器版本：Chrome 100.0.4896.75
系统：Win10 专业工作站版
版本号：21H1

**Comment by shuax** [comment]
没有相关改动，还有其他人遇到这个问题吗

**Comment by Soizzer** [comment]
> 没有相关改动，还有其他人遇到这个问题吗

今天用1.5也遇到这个问题了。不知道是什么情况，以前用Chrome99版+1.4.2的时候从来没遇到过这个问题，
或许是Chrome100有些什么问题吧，我再用一段时间试试看。
