### ISSUE TITLE
可以添加右键关闭标签页功能吗？

### ISSUE THREAD

**Issue by n3060130112** [shuax/chrome_plus#9]
可以添加右键关闭标签页功能吗？

**Comment by shuax** [comment]
没有加的打算，看有没有网友改一个出来吧。

**Comment by Soizzer** [comment]
Chrome

> 可以添加右键关闭标签页功能吗？

Chrome不是自带右键关闭标签吗？？快捷键是Ctrl+W

**Comment by klgd** [comment]
https://github.com/shuax/chrome_plus/blob/fadc91cdf8dd785d05535beaa5f2fae0a3dec75f/src/TabBookmark.h#L419

改为   
```
if (wParam == WM_LBUTTONDBLCLK || wParam == WM_RBUTTONDOWN)
```
